ruby_on_rails = Language.create(name: "Ruby on Rails", id: 1)
angular = Language.create(name: "Angular.js", id: 2)
ruby = Language.create(name: "Ruby", id: 3)
javascript = Language.create(name: "Javascript", id: 4)
jQuery = Language.create(name: "jQuery", id: 5)
general = Language.create(name: "General / All Languages", id: 6)

projects = Project.create([
  { name: "Betastore", in_progress: false,
    description: "E-commerce app written during back-end web course at Betamore. Because it was a back-end course, we did not spend a lot of time on design and instead used bootstrap. We used PostgreSQL as our database, Braintree for processing payments, and Sidekiq for performing background jobs. ",
    url: "http://brandonbetastore.herokuapp.com",
    github_link: "http://github.com/brandonclosson/betastore",
    language: ruby_on_rails
  },
  {
    name: "Dwidder", in_progress: true,
    description: "This is a twitter clone I am building with the aid of Michael Hartl's free online guide. I took a break from the guide to finish the Betamore Ruby on Rails course and learn some Javascript, so this is a work in progress. The example app written by Hartl is very heavily tested, so I have been using it as a beginner's guide to TDD.",
    github_link: "http://github.com/brandonclosson/dwidder",
    language: ruby_on_rails
  },
  { name: "Angular Store", in_progress: false,
    description: "A very tiny Angular app based on <a href=\"https://www.codeschool.com/courses/shaping-up-with-angular-js\">Code School's course</a> on building a responsive store selling expensive gems and stones using Angular. My store has a different but equally superfluous theme.",
    github_link: "http://github.com/brandonclosson/mini-angular-store",
    language: angular
  },
  {
    name: "Learn Ruby by Test First", in_progress: false,
    description: "Sixteen exercises downloaded from <a href=\"http://testfirst.org/learn_ruby\">testfirst.org</a> showing basic understanding of object oriented Ruby.",
    language: ruby,
    github_link: "https://github.com/brandonclosson/learn_ruby"
  },
  {
    name: "jQuery Image Slider", in_progress: false,
    description: "While working on various challenges on the <a href=\"http://www.theodinproject.com/\">Odin Project</a>, I created this very simple image slider using jQuery.",
    github_link: "http://github.com/brandonclosson/odin_projects/jquery_slider",
    language: jQuery
  },
  {
    name: "jQuery Colorful Grid", in_progress: false,
    description: "Also a part of the <a href=\"http://www.theodinproject.com/\"></a>, this is just a grid generated by jQuery which cells change color when hovered over. The size of the grid is set by the user.",
    github_link: "http://github.com/brandonclosson/odinprojects/jquery_grid",
    language: jQuery
  }
])

bookmarks = Bookmark.create([
  {
    name: "Code School", language: general, url: "http://www.codeschool.com",
    description: "At first I was hesitant about learning online, but I have come to really enjoy using code school for learning the basics of a new language quickly."
  },
  {
    name: "Quora", language: general, url:"http://www.quora.com",
    description: "Quora is an amazing resource for beginners, with loads of programmers who want to help."
  },
  {
    name: "Rails Edge Guides", language: ruby, url: "http://edgeguides.rubyonrails.org/",
    description: "The Rails guides are amazing to read through after becoming somewhat familiar with the structure of Rails, the Edge guides are more exciting but less official."
  },
  {
    name: "Javascript Kit", language: javascript, url: "http://www.javascriptkit.com/",
    description: "Although it seems and often is outdated, these example scripts are great when just starting out with javascript to get ideas as to what it can actually accomplish on a small scale."
  }
])